name: CI
on: [push]
jobs:
  GuessingGameTests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/guessing_game
    steps:
      - uses: actions/checkout@v2
      - name: Update Repositories && Install libs
        run: sudo apt-get update && sudo apt install libncurses5
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '24.0'
          elixir-version: '1.12.2'
          experimental-otp: true
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix test
